In [1]:
import torch

In [2]:
N = torch.zeros((27, 27), dtype=torch.int32)
# Let's examine our tensor N
print("Our tensor N:")
print(f"Shape: {N.shape}")        # Dimensions of the tensor
print(f"Data type: {N.dtype}")    # What type of numbers it stores
print(f"Device: {N.device}")      # CPU vs GPU
print(f"Total elements: {N.numel()}")  # Total number of elements

# Let's see what it looks like (first 5 rows and columns)
print("\nFirst 5x5 portion of N:")
print(N[:5, :5])

Our tensor N:
Shape: torch.Size([27, 27])
Data type: torch.int32
Device: cpu
Total elements: 729

First 5x5 portion of N:
tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)


In [3]:
# Let's create different types of tensors to understand the basics
print("=== Creating Different Tensors ===")

# 1. Different ways to make tensors
zeros = torch.zeros(3, 4)           # 3x4 matrix of zeros
ones = torch.ones(2, 3)             # 2x3 matrix of ones  
random = torch.randn(2, 2)          # 2x2 random normal distribution
from_list = torch.tensor([1, 2, 3, 4])
from_2dlist = torch.tensor([[1, 2], [1, 2]])  # From Python list

print("Zeros (3x4):")
print(zeros)
print("\nOnes (2x3):")  
print(ones)
print("\nRandom (2x2):")
print(random)
print("\nFrom list:")
print(from_list)
print("\nFrom 2D list:")
print(from_2dlist)
print("Shape:", from_2dlist.shape)

=== Creating Different Tensors ===
Zeros (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Random (2x2):
tensor([[ 0.6585, -0.0222],
        [-0.5263, -0.3691]])

From list:
tensor([1, 2, 3, 4])

From 2D list:
tensor([[1, 2],
        [1, 2]])
Shape: torch.Size([2, 2])


In [4]:
# Let's play with indexing and slicing (like numpy arrays)
print("=== Indexing and Slicing ===")

# Create a small tensor to experiment with
small = torch.arange(12).reshape(3, 4)  # Numbers 0-11 in 3x4 shape
print("Our test tensor:")
print(small)

# Indexing examples
print(f"\nElement at [1,2]: {small[1, 2]}")           # Single element
print(f"First row: {small[0, :]}")                    # Entire first row  
print(f"Second column: {small[:, 1]}")                # Entire second column
print(f"Top-left 2x2: \n{small[:2, :2]}")           # 2x2 submatrix

# You can also modify parts of tensors
small[0, 0] = 999
print(f"\nAfter changing [0,0] to 999:")
print(small)

=== Indexing and Slicing ===
Our test tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Element at [1,2]: 6
First row: tensor([0, 1, 2, 3])
Second column: tensor([1, 5, 9])
Top-left 2x2: 
tensor([[0, 1],
        [4, 5]])

After changing [0,0] to 999:
tensor([[999,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]])


In [5]:
# Basic tensor operations
print("=== Basic Tensor Operations ===")

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print("a =", a)
print("b =", b)

# Element-wise operations
print(f"\na + b = {a + b}")           # Addition
print(f"a * b = {a * b}")             # Element-wise multiplication  
print(f"a ** 2 = {a ** 2}")           # Squaring

# Matrix operations
matrix1 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float)
matrix2 = torch.tensor([[5, 6], [7, 8]], dtype=torch.float)

print(f"\nMatrix multiplication:")
print(f"matrix1 @ matrix2 = \n{matrix1 @ matrix2}")

# Useful tensor methods
print(f"\nUseful operations:")
print(f"Sum: {a.sum()}")
print(f"Mean of matrix1: {matrix1.mean()}")
print(f"Max of a: {a.max()}")
print(f"Shape of matrix1: {matrix1.shape}")

=== Basic Tensor Operations ===
a = tensor([1, 2, 3])
b = tensor([4, 5, 6])

a + b = tensor([5, 7, 9])
a * b = tensor([ 4, 10, 18])
a ** 2 = tensor([1, 4, 9])

Matrix multiplication:
matrix1 @ matrix2 = 
tensor([[19., 22.],
        [43., 50.]])

Useful operations:
Sum: 6
Mean of matrix1: 2.5
Max of a: 3
Shape of matrix1: torch.Size([2, 2])


In [6]:
# Now let's understand what your N tensor is for!
print("=== Understanding the N tensor in context ===")

# Your N is a 27x27 matrix. Why 27? Let's figure it out!
# It's probably for the 26 letters + 1 special character (like '.')

alphabet = 'abcdefghijklmnopqrstuvwxyz'
print(f"Alphabet has {len(alphabet)} letters")
print(f"With the '.' character, that's {len(alphabet) + 1} = 27 total")

# Let's create a mapping
chars = ['.'] + list(alphabet) 
print(f"Our character set: {chars}")
print(f"Total characters: {len(chars)}")

# Create char to index mapping
char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for i, ch in enumerate(chars)}

print(f"\nChar to index examples:")
print(f"'.' -> {char_to_idx['.']}")
print(f"'a' -> {char_to_idx['a']}")  
print(f"'z' -> {char_to_idx['z']}")

print(f"\nSo N[i,j] will count how often character i is followed by character j!")

=== Understanding the N tensor in context ===
Alphabet has 26 letters
With the '.' character, that's 27 = 27 total
Our character set: ['.', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
Total characters: 27

Char to index examples:
'.' -> 0
'a' -> 1
'z' -> 26

So N[i,j] will count how often character i is followed by character j!


## 🎮 Your Turn to Experiment!

Try running each cell above to see how tensors work. Here are some fun experiments you can try:

1. **Modify the tensors**: Change the numbers in the tensor creation cells
2. **Try different operations**: Add `.transpose()`, `.reshape()`, or `.view()` to existing tensors  
3. **Experiment with indexing**: Try `N[0:5, 10:15]` to see different parts of your N matrix
4. **Check data types**: Try `torch.zeros((3,3), dtype=torch.float64)` vs `torch.int8`

The next cell is a playground for you!

In [7]:
# 🧪 PLAYGROUND - Experiment here!
# Try anything you want with tensors

# Example experiments you can try:
# 1. Create your own tensor
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("My tensor:", my_tensor)

# 2. Try some operations
print("Shape:", my_tensor.shape)
print("Transposed:", my_tensor.T)

# Your experiments below:

My tensor: tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
Transposed: tensor([[1, 4],
        [2, 5],
        [3, 6]])
